
all:
	@echo You wish to install the bind or walled garden log scrapper
	@echo make bind, make garden, or make bind garden.

bind:	.dummy
	$(MAKE) -C bind-scrapper

garden:	.dummy
	$(MAKE) -C walled-garden-scrapper

.dummy:

