
=head1 Configuration Files

This area contains example configuration files.

RPZLA involves the configuration of local BIND resolvers
that use RPZ (see the bind/ sub-dir), and analysis site
at which you can view your data (see the analyse/ sub-dir)
and probably a walled garden site (see the walled-garden/
sub-dir).

For each system that is a BIND resolver, walled garden or
analysis site the 

  /etc/rpzla/rpzla.conf 
  
file needs to be installed.

It provides the details of database connectivity, log file
locations for parsing and the URL detials for the analysis
site.
