
=head1 PostgreSQL

=head2 Creating the Database

The database needs tables, views, indexes etc..

These can be created with:

  sudo ./create_structures.pl

To do that, B<and> upload the sample data, use:

  db_all.sh

There is an inverse for create_structures.pl, destroy_structures.pl
which will destroy everything (database, roles etc.)
